Web/Models/ErrorViewModel.cs
namespace Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Web/Controllers/BookController.cs
using Core.Entity;
using Core.Model;
using Core.Rest;
using Microsoft.AspNetCore.Mvc;

namespace Web.Controllers
{
    public class BookController : Controller
    {
        private readonly IRestService _service;
        public BookController(IRestService service)
        {
            _service = service;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Search(string bookName, string authorName, string isbn)
        {
            var result = await _service.Get<List<BookWebResponse>>(
                $"book?Author={authorName}&" +
                $"Name={bookName}&" +
                $"Isbn={isbn}");

            return Json(result);
        }
        [HttpPost]
        public async Task<IActionResult> Add(AddBookTransactionWebRequest request)
        {
            return Json(await _service.Post<BookTransaction>($"booktransaction", request));
        }
        [HttpGet]
        public async Task<IActionResult> MemberList()
        {
            return Json(await _service.Get<List<MemberWebResponse>>($"member"));
        }
    }
}

Web/Controllers/BookTransactionController.cs
using Core.Model;
using Core.Rest;
using Microsoft.AspNetCore.Mvc;

namespace Web.Controllers
{
    public class BookTransactionController : Controller
    {
        private readonly IRestService _service;
        public BookTransactionController(IRestService service)
        {
            _service = service;
        }

        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> Search(string first, string second)
        {
            var parseFirst = DateTime.Parse(first);
            var parseSecond = DateTime.Parse(second);


            return Json(await _service.Get<List<BookTransactionWebResponse>>($"booktransaction?FirstDate={first}&SecondDate={second}"));
        }
    }
}

Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Web.Models;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Web/Views/Book/Index.cshtml
@section scripts {
    <script src="~/js/book.js"></script>
}

    <div class="row">
        <div class="col-3">
            <label>Yazar</label>
            <input type="text" id="author" class="form-control" />
        </div>
        <div class="col-3">
            <label>Kitap Adı</label>
            <input type="text" id="book" class="form-control" />
        </div>
        <div class="col-3">
            <label>Isbn</label>
            <input type="text" id="isbn" class="form-control" />
        </div>
        <div class="col-3">
            <label>Filtrele</label>
            <br />
            <button class="btn btn-success" type="button" onclick="SearchBook();">Ara</button>
        </div>
    </div>
    <br />
    <table class="table" id="bookList">
        <thead>
            <tr>
                <th>Kitap Adı</th>
                <th>Yazarı</th>
                <th>Isbn</th>
                <th>İşlemler</th>
            </tr>
        </thead>
    </table>
    <div class="modal" tabindex="-1" role="dialog" id="memberModal">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content rounded">
                <div class="modal-header">
                    <h5 class="modal-title">Kayıt  </h5>
                </div>
                <br />
                <div class="modal-body scroll-y px-10 px-lg-15 pt-0 pb-15">
                    <input type="hidden" id="isbn" name="isbn"/>
                    <select class="form-control" id="memberDropdown">
                    </select>
                    <br />
                    <button class="btn btn-success" onclick="SaveBookTransaction();">Kaydet</button>
                </div>
            </div>
        </div>
    </div>

Web/Views/BookTransaction/Index.cshtml
@section Scripts {
    <script src="~/js/booktransaction.js"></script>
}

    <div class="row">
        <div class="col-4">
            <label>Başlangıç Tarihi</label>
            <input type="date" id="firstDate" class="form-control" value="@DateTime.Now.AddDays(-30).ToString("yyyy-mm-dd")" />
        </div>
        <div class="col-4">
            <label>Bitiş Tarihi</label>
            <input type="date" id="secondDate" class="form-control" value="@DateTime.Now.ToString("yyyy-mm-dd")" />
        </div>
        <div class="col-4">
            <label>Filtrele</label><br />
            <button class="btn btn-success" onclick="SearchBookTransaction();">Ara</button>
        </div>
    </div>
    <br />
    <table class="table" id="bookTransactionList">
        <thead>
            <tr>
                <th>Kitap Adı</th>
                <th>Üye Adı</th>
                <th>Veriliş Tarihi</th>
                <th>İade Tarihi</th>
                <th>Ceza Tutarı</th>
            </tr>
        </thead>
    </table>

Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Anasayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BookTransaction" asp-action="Index">Rapor</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("scripts", required: false)
</body>
</html>